spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/review
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


